# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f7164b65dbddfce01a9f5272436fa217f299f8eaddadbb117aeddf34b71dd37b3fc69c380f4316c5e0473383dda7807ae773b5f6776a43239ad0f3abe0ee7d1

test:
  secret_key_base: b7dc7880bd5fad33e14c471b33624a902594e19ab76843c2cf96d2dc1eada5423ab9263395826e784557cdb324b93af84b5beba773194aa4f8e4d3db0d48044e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
